### ISSUE TITLE
Messages should provide the tag number of each field

### ISSUE THREAD

**Issue by sigurdm** [google/protobuf.dart#146]
This is needed to make the protoc_plugin generate doc-comments, as the descriptors has lists with items indexing like this.

This is also provided at least by the c++ code generator.

**Comment by osa1** [comment]
We have this information in https://github.com/google/protobuf.dart/blob/5e1a422e39476884861a2137b0d7241315889299/protobuf/lib/src/protobuf/builder_info.dart#L15-L16

The map should be 1-1 and the inverse of it can be computed when needed.
