### ISSUE TITLE
provide a way to retrieve all enum values

### ISSUE THREAD

**Issue by d3v-cl** [google/protobuf.dart#151]
I am looking for a way to retrieve all enum values from the fieldInfos.

I can easily get the default value, but the values() function is static and AFAIC there is no easy way (without mirrors) to call this static values() function from the default enum value.

**Comment by osa1** [comment]
I think [`FieldInfo.enumValues`](https://pub.dev/documentation/protobuf/latest/protobuf/FieldInfo/enumValues.html) is exactly this. It's not documented in the pub.dev page but I recently documented this field in b7f9569bd3cd709fc1a77dedd9b407def7a2b461 so it will be documented in the pub.dev page with the next release.

Please feel free to re-open if I misunderstand the issue and what you're looking for is not `FieldInfo.enumValues`.
