### ISSUE TITLE
Comments from .proto files should move over to dart

### ISSUE THREAD

**Issue by ened** [google/protobuf.dart#161]
Given this enum defined in a proto file:

``` proto
// Defines the response status for a IAP operation.
enum IAPResponseStatus {
    // All went well, see the other fields for response details.
    ok = 0;

    // Fatal error during the API action.
    error = 1;

    // (iOS only) Library user needs to fetch the list of products from the store first.
    emptyProductList = 2;

    // In-App purchases not available (device or policy constraints etc).
    disabled = 3;
}
```

Then this plugin currently generates:

``` dart
class IAPResponseStatus extends $pb.ProtobufEnum {
  static const IAPResponseStatus ok = const IAPResponseStatus._(0, 'ok');
  static const IAPResponseStatus error = const IAPResponseStatus._(1, 'error');
  static const IAPResponseStatus emptyProductList = const IAPResponseStatus._(2, 'emptyProductList');
  static const IAPResponseStatus disabled = const IAPResponseStatus._(3, 'disabled');
}
```

However, it should generate:

``` dart
/// Defines the response status for a IAP operation.
class IAPResponseStatus extends $pb.ProtobufEnum {
  /// All went well, see the other fields for response details.
  static const IAPResponseStatus ok = const IAPResponseStatus._(0, 'ok');
  /// Fatal error during the API action.
  static const IAPResponseStatus error = const IAPResponseStatus._(1, 'error');
  /// (iOS only) Library user needs to fetch the list of products from the store first.
  static const IAPResponseStatus emptyProductList = const IAPResponseStatus._(2, 'emptyProductList');
  /// In-App purchases not available (device or policy constraints etc).
  static const IAPResponseStatus disabled = const IAPResponseStatus._(3, 'disabled');
}
```

**Comment by v0l** [comment]
With gRPC  this would be very helpful to copy all the comments from rpc methods into the dart code!

**Comment by armiol** [comment]
Is this still considered for implementation? We are struggling with the comments not being transferred to the Dart output as well.

**Comment by sigurdm** [comment]
It would be awesome to support I agree. Currently we don't have a lot of resources, so don't expect it to happen soon.

**Comment by MattyBoy4444** [comment]
Any news on this?

**Comment by bartekpacia** [comment]
This would be a very useful feature.

I'll offer a use case I have: I generate [the Selector class](https://pub.dev/documentation/patrol/latest/patrol/Selector-class.html) from [the .proto file](https://github.com/leancodepl/patrol/blob/master/contracts.proto), and it's part of my package's public API. Unfortunately, I cannot add doc comments to it, because well... it's generated.

Tagging @sigurdm – I've seen you're activate on Dart related repos on `dart-lang` and `google`. I hope you can find some resources to implement this 🙏🏻

**Comment by bartekpacia** [comment]
Sure, I understand. 

If Google can't do this because it's not an important issue for you... is this repository accepting contributions?

**Comment by sigurdm** [comment]
I will defer to @osa1 who is working in this now.

**Comment by kevmoo** [comment]
I'd LOVE to have this, too.

**Comment by bartekpacia** [comment]
Wow, awesome! Thanks!

**Comment by kevmoo** [comment]
> Wow, awesome! Thanks @kevmoo!

There is some more work we could do here. Like making the comment references to other types work. Let's file separate issues for those.
