### ISSUE TITLE
query_benchmark should run on chrome instead of d8 when using dart2js.

### ISSUE THREAD

**Issue by sigurdm** [google/protobuf.dart#222]
This change needs to happen in the golem config.
Json works differently between these platforms - we want to optimize for chrome.

cc @rakudrama @sortie

**Comment by osa1** [comment]
Golem is internal to Google. We should migrate this issue to somewhere internal and close it. Any thoughts on this @sigurdm ?

For documenting running query_benchmark we have #613.

**Comment by rakudrama** [comment]
It should tun on both `d8` and `chrome`.

I'm curious how JSON works differently between `d8` and `chrome` - it might be helpful to understand the differences for `dart:convert`.

**Comment by osa1** [comment]
Moved issue to buganizer 229956165. Problems with documentation or running the benchmarks manually will be fixed with #613.

**Comment by mraleph** [comment]
> I'm curious how JSON works differently between `d8` and `chrome` - it might be helpful to understand the differences for `dart:convert`.

I doubt there should be any difference between JSON in `d8` or `chrome`. JSON parsing is implemented in V8 in C++ so there should be no difference. 

The only thing I could think of is that string representation might be different (e.g. string arriving over network might be a n external string) but again that should not change much. 

@sigurdm Sigurd, do you remember what you meant by JSON working differently?

**Comment by sigurdm** [comment]
> @sigurdm Sigurd, do you remember what you meant by JSON working differently?

No - unfortunately. I remember someone (@rakudrama ?) mentioning that it might make a difference, somehow the embedding was responsible for parsing json or something. I was surprised to learn that as well. I might have misunderstood something.
