### ISSUE TITLE
Compare operator does not handle cleared lists

### ISSUE THREAD

**Issue by andreilitvin** [google/protobuf.dart#24]
Assume the protobuffer test.proto:

``` proto
syntax = "proto2";

message Simple {
  optional string name = 1;
  repeated int32 values = 2;
}
```

This will fail the '==' test (serialization is ok, however compare seems to differentiate between 'empty list' and 'list never initialized'). I would expect: if object type and serialization is identical, then objects should be identical:

``` dart
library simple_test;

import 'package:unittest/unittest.dart';
import 'test.pb.dart';

void main() {
  Simple s1 = new Simple()
      ..name = 'Name'
      ;

  Simple s2 = new Simple()
      ..name = 'Name'
      ..values.clear() // redundant
      ;

  test('Json', () => expect(s1.writeToJson(), equals(s2.writeToJson())));
  test('==', () => expect(s1, equals(s2)));   // FAILS!
  test('Buffer', () => expect(s1.writeToBuffer(), equals(s2.writeToBuffer())));
}
```

**Comment by osa1** [comment]
This issue is using an ancient version of the library. When I try the repro with the current version it works as expected. Closing.
