### ISSUE TITLE
Lint warnings 'Avoid const keyword' and 'Annotate overriden members'

### ISSUE THREAD

**Issue by shinayser** [google/protobuf.dart#333]
A have a project that has over a thousand of those lint warnings.
Example:

![image](https://user-images.githubusercontent.com/1146982/71130522-d5acb080-21d0-11ea-93cb-13995619666a.png)
![image](https://user-images.githubusercontent.com/1146982/71130566-fd9c1400-21d0-11ea-9770-abe342647324.png)

**Comment by emadfarag** [comment]
This will solve the linter warnings for extra consts: https://github.com/dart-lang/protobuf/pull/352

**Comment by shinayser** [comment]
Any information on this issue?

**Comment by fzyzcjy** [comment]
Any updates? It is still there...
![image](https://user-images.githubusercontent.com/5236035/110325949-f7eb5200-8052-11eb-9e4b-60c5be885b29.png)

**Comment by fzyzcjy** [comment]
Oh a suppress lint is added (not sure why it disappeared temporarily, but now it is ok)

![image](https://user-images.githubusercontent.com/5236035/110326249-5c0e1600-8053-11eb-8fbc-4332654c894b.png)

**Comment by osa1** [comment]
Recent versions of the plugin should generate the relevant `ignore_for_file`s to suppress all of these warnings. Please reopen if you get warnings with the latest release.
