### ISSUE TITLE
hashCode is problematic

### ISSUE THREAD

**Issue by chirayuk** [google/protobuf.dart#34]
The current implementation of `hashCode` in generated_message.dart hashes the values of the fields of the protobuf – https://github.com/dart-lang/dart-protobuf/blob/f821faf77a3d273255a76ea723a46f390d1a89f8/lib/src/protobuf/generated_message.dart#L291.  This prevents its use as a map key or in a set since a protobuf is mutable.  Perhaps the `hashCode` getter should not be abused this way and this functionality should be moved into a regular method (e.g. "hash()") to avoid this issue.  In the current state, it only makes sense if the protobuf itself is immutable.

**Comment by skybrian** [comment]
You are right, but I think the solution is to avoid mutating protos that are used as keys to maps. For now this is up to the user, but perhaps we will add a freeze() method that prevents mutation.

**Comment by osa1** [comment]
You can now use `GeneratedMessage.freeze` when you need `hashCode` of a message to be stable.
