### ISSUE TITLE
Travis builds are failing to due lints/hints

### ISSUE THREAD

**Issue by jakemac53** [google/protobuf.dart#346]
Looks like its been failing for a couple months https://travis-ci.org/dart-lang/protobuf/builds

**Comment by iinozemtsev** [comment]
I wanted to contribute some lint fixes, but looks like some checks are incompatible with minimal sdk requirements (or some other config?), e.g. fixing `prefer_spread_collections` generates an error `This requires the 'spread-collections' experiment to be enabled.`

Also the [first red](https://travis-ci.org/dart-lang/protobuf/jobs/621253857) does not contain any changes to project settings, the only noticeable difference is dart sdk version change from 2.7.0-dev-1.0 to 2.7.0-dev-2.1

**Comment by iinozemtsev** [comment]
ah, it must be broken by https://github.com/dart-lang/pedantic/commit/9943913a1685065894eaf1b5bdfa53f53c8b147c

**Comment by iinozemtsev** [comment]
I've sent https://github.com/dart-lang/protobuf/pull/348

**Comment by osa1** [comment]
We no longer use Travis CI.
