### ISSUE TITLE
Missing concrete implementation of 'GeneratedMessage.createEmptyInstance

### ISSUE THREAD

**Issue by hjlp20150803** [google/protobuf.dart#371]
I use "protoc  ./*.proto --dart_out=grpc:./dart" to generate the dart file, it met the errors:
"Missing concrete implementation of 'GeneratedMessage.createEmptyInstance'.
Try implementing the missing method, or make the class abstract.dartnon_abstract_class_inherits_abstract_member"

The proto source file and dart file like below, it shows error on LoadKeysRequest, but what's wrong and how to fix?

===========================================
syntax = "proto3";
package bridge;

message LoadKeysRequest {
	string Addr = 1; 
	string RPass = 2; 
	string IPass = 3; 
	string N = 4;
	string U = 5;
}

=====================================================
protoc --version
libprotoc 3.11.4
=====================================================
///
//  Generated code. Do not modify.
///
// ignore_for_file: non_constant_identifier_names,library_prefixes
library bridge_agent;

// ignore: UNUSED_SHOWN_NAME
import 'dart:core' show int, bool, double, String, List, override;

import 'package:fixnum/fixnum.dart';
import 'package:protobuf/protobuf.dart';

class LoadKeysRequest extends GeneratedMessage {
  static final BuilderInfo _i = new BuilderInfo('LoadKeysRequest')
    ..aOS(1, 'addr')
    ..aOS(2, 'rPass')
    ..aOS(3, 'iPass')
    ..aOS(4, 'n')
    ..aOS(5, 'u')
    ..hasRequiredFields = false
  ;

  LoadKeysRequest() : super();
  LoadKeysRequest.fromBuffer(List<int> i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromBuffer(i, r);
  LoadKeysRequest.fromJson(String i, [ExtensionRegistry r = ExtensionRegistry.EMPTY]) : super.fromJson(i, r);
  LoadKeysRequest clone() => new LoadKeysRequest()..mergeFromMessage(this);
  BuilderInfo get info_ => _i;
  static LoadKeysRequest create() => new LoadKeysRequest();
  static PbList<LoadKeysRequest> createRepeated() => new PbList<LoadKeysRequest>();
  static LoadKeysRequest getDefault() {
    if (_defaultInstance == null) _defaultInstance = new _ReadonlyLoadKeysRequest();
    return _defaultInstance;
  }
  static LoadKeysRequest _defaultInstance;
  static void $checkItem(LoadKeysRequest v) {
    if (v is! LoadKeysRequest) checkItemFailed(v, 'LoadKeysRequest');
  }

  String get addr => $_getS(0, '');
  set addr(String v) { $_setString(0, v); }
  bool hasAddr() => $_has(0);
  void clearAddr() => clearField(1);

  String get rPass => $_getS(1, '');
  set rPass(String v) { $_setString(1, v); }
  bool hasRPass() => $_has(1);
  void clearRPass() => clearField(2);

  String get iPass => $_getS(2, '');
  set iPass(String v) { $_setString(2, v); }
  bool hasIPass() => $_has(2);
  void clearIPass() => clearField(3);

  String get n => $_getS(3, '');
  set n(String v) { $_setString(3, v); }
  bool hasN() => $_has(3);
  void clearN() => clearField(4);

  String get u => $_getS(4, '');
  set u(String v) { $_setString(4, v); }
  bool hasU() => $_has(4);
  void clearU() => clearField(5);
}

**Comment by hjlp20150803** [comment]
Project is good,after several upgrading of flutter or some package it goes wrong. Even if use the old version it still goes wrong.Can I stop flutter's upgrading?

**Comment by sigurdm** [comment]
> Can I stop flutter's upgrading?

Not sure I understand this question.
Can you post your `pubspec.yaml`, flutter version and `package:protobuf` version?

**Comment by sigurdm** [comment]
For sure the error looks like a version mismatch between your `package:protoc_plugin` and `package:protobuf`.

**Comment by hjlp20150803** [comment]
protoc --version
libprotoc 3.11.4

**Comment by hjlp20150803** [comment]
$ flutter version
1.18.0-11.1.pre
1.17.1
1.19.0-1.0.pre
1.19.0-0.0.pre
1.18.0-13.0.pre
1.18.0-12.0.pre
1.18.0-11.0.pre
1.18.0-9.0.pre
1.18.0-10.0.pre
1.17.0-3.4.pre

**Comment by hjlp20150803** [comment]
name: vanilla
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  process_run: ^0.10.8
  video_player: ^0.10.9+2
  chewie: ^0.9.8+1
  random_words: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  #flutter_architecture_samples:
  #  path: ../../
  #todos_repository_flutter:
  #  path: ../todos_repository_flutter
  #protobuf: "^0.8.0"
  protobuf: ^1.0.1
  # protoc_plugin: ^19.0.1
  #grpc: "^0.4.1"
  grpc: ^2.1.3
  fixnum: ^0.10.11
  path_provider: ^1.6.7
  cupertino_icons: ^0.1.2
  image: ^2.0.5
  #image_picker: ^0.4.10
  #flutter_image_pick_crop: ^0.0.1
  #flutter_multiple_image_picker: ^0.0.1
  #encrypt: ^0.2.0
  #shrine_images: 1.0.0
  #file_picker: ^0.1.3
  file_picker: ^1.9.0+1
  permission: ^0.1.0
  #photo_view: ^0.5.0

dev_dependencies:
  #mockito: ">=2.2.0 <3.0.0"
  mockito: ^4.0.0
  #test: ^0.12.0
  test: ^1.5.1+1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  #integration_tests:
  #  path: ../integration_tests


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    # https://unsplash.com/photos/EN2PucB2yhA
    - assets/ronnie-mayo-361348-unsplash.jpg
    # https://unsplash.com/photos/pmH_Y4Qetrk
    - assets/stefan-stefancik-105587-unsplash.jpg
    # https://unsplash.com/photos/5ditmO9_ae0
    - assets/simon-fitall-530083-unsplash.jpg
    # https://unsplash.com/photos/3MNzGlQM7qs
    - assets/anton-repponen-99530-unsplash.jpg
    # https://unsplash.com/photos/CPjkWSD0RM0
    - assets/kevin-cochran-524957-unsplash.jpg
    # https://unsplash.com/photos/T0XLKgpyT_c
    - assets/samsommer-72299-unsplash.jpg
    # https://unsplash.com/photos/twukN12EN7c
    - assets/simon-matzinger-320332-unsplash.jpg
    # https://unsplash.com/photos/8BH_M-53CyA
    - assets/meng-ji-102492-unsplash.jpg
    # https://unsplash.com/photos/tvOvBq90bM0
    - assets/brady-bellini-212790-unsplash.jpg
    - assets/products/backpack.png
    - assets/products/beachball.png
    - assets/products/binoculars.png
    - assets/products/brush.png
    - assets/products/chair.png
    - assets/products/chucks.png
    - assets/products/clock.png
    - assets/products/fish_bowl.png
    - assets/products/flippers.png
    - assets/products/green-shoes.png
    - assets/products/heels.png
    - assets/products/helmet.png
    - assets/products/lawn_chair.png
    - assets/products/lipstick.png
    - assets/products/popsicle.png
    - assets/products/radio.png
    - assets/products/sunnies.png
    - assets/products/surfboard.png
    - assets/products/teapot.png
    - assets/diamond.png
    - assets/slanted_menu.png
    - assets/zach.jpg
    - assets/16c477b.jpg
    - assets/ali-connors.png
    - assets/peter-carlsson.png
    - assets/shrine_images/0-0.jpg
    - assets/shrine_images/1-0.jpg
    - assets/shrine_images/2-0.jpg
    - assets/shrine_images/3-0.jpg
    - assets/shrine_images/4-0.jpg
    - assets/shrine_images/5-0.jpg
    - assets/shrine_images/6-0.jpg
    - assets/shrine_images/7-0.jpg
    - assets/shrine_images/8-0.jpg
    - assets/shrine_images/9-0.jpg
    - assets/shrine_images/10-0.jpg
    - assets/shrine_images/11-0.jpg
    - assets/shrine_images/12-0.jpg
    - assets/shrine_images/13-0.jpg
    - assets/shrine_images/14-0.jpg
    - assets/shrine_images/15-0.jpg
    - assets/shrine_images/16-0.jpg
    - assets/shrine_images/17-0.jpg
    - assets/shrine_images/18-0.jpg
    - assets/shrine_images/19-0.jpg
    - assets/shrine_images/20-0.jpg
    - assets/shrine_images/21-0.jpg
    - assets/shrine_images/22-0.jpg
    - assets/shrine_images/23-0.jpg
    - assets/shrine_images/24-0.jpg
    - assets/shrine_images/25-0.jpg
    - assets/shrine_images/26-0.jpg
    - assets/shrine_images/27-0.jpg
    - assets/shrine_images/28-0.jpg
    - assets/shrine_images/29-0.jpg
    - assets/shrine_images/30-0.jpg
    - assets/shrine_images/31-0.jpg
    - assets/shrine_images/32-0.jpg
    - assets/shrine_images/33-0.jpg
    - assets/shrine_images/34-0.jpg
    - assets/shrine_images/35-0.jpg
    - assets/shrine_images/36-0.jpg
    - assets/shrine_images/37-0.jpg
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `assets/PACKAGE_NAME/`. The `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

**Comment by hjlp20150803** [comment]
I have post the flutter version and pubspec.yaml in https://github.com/dart-lang/protobuf/issues/371, <https://github.com/dart-lang/protobuf/issues/371,please>please take a look, thanks.

**Comment by sigurdm** [comment]
Please use code fences: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks .
It is very hard to read without.

**Comment by sigurdm** [comment]
Probably you have activated an older protoc_plugin.

Try running `pub global activate protoc_plugin 19.0.1`.

**Comment by hjlp20150803** [comment]
It still stays on old version, what's wrong
==========================
$ pub global activate protoc_plugin 19.0.1
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies...
Package protoc_plugin has no versions that match 19.0.1 derived from:
- pub global activate depends on version 19.0.1

**Comment by hjlp20150803** [comment]
It still stays on old version, what's wrong

$ pub global activate protoc_plugin 19.0.1
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies...
Package protoc_plugin has no versions that match 19.0.1 derived from:
- pub global activate depends on version 19.0.1

**Comment by hjlp20150803** [comment]
> Probably you have activated an older protoc_plugin.
> 
> Try running `pub global activate protoc_plugin 19.0.1`.

I think maybe you are right, it still stays on old version, but I failed to upgrade to new version:
```
$ pub global activate protoc_plugin
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies... (1.4s)
+ analyzer 0.30.0+4 (0.39.8 available)
+ args 1.5.1 (1.6.0 available)
+ async 2.0.1 (2.4.1 available)
+ charcode 1.1.2 (1.1.3 available)
+ cli_util 0.1.3 (0.1.4 available)
+ collection 1.14.6 (1.14.12 available)
+ convert 2.1.1
+ crypto 2.0.2+1 (2.1.5 available)
+ csslib 0.14.3 (0.16.1 available)
+ dart_style 1.0.9+1 (1.3.6 available)
+ fixnum 0.10.7 (0.10.11 available)
+ front_end 0.1.0-alpha.4.1 (0.1.29 available)
+ glob 1.1.7 (1.2.0 available)
+ html 0.13.3 (0.14.0+3 available)
+ isolate 1.1.0 (2.0.3 available)
+ kernel 0.3.0-alpha.1.1 (0.3.29 available)
+ logging 0.11.3+2 (0.11.4 available)
+ meta 1.1.8
+ package_config 1.0.3 (1.9.3 available)
+ path 1.5.1 (1.7.0 available)
+ plugin 0.2.0+3
+ protobuf 0.7.2 (1.0.1 available)
+ protoc_plugin 0.7.11 (19.0.1 available)
+ source_span 1.5.5 (1.7.0 available)
+ string_scanner 1.0.4 (1.0.5 available)
+ term_glyph 1.1.0
+ typed_data 1.1.5 (1.1.6 available)
+ utf 0.9.0+3 (0.9.0+5 available)
+ watcher 0.9.7+6 (0.9.7+15 available)
+ yaml 2.1.13 (2.2.1 available)
Precompiling executables...
Loading source assets...
Precompiled protoc_plugin:protoc_plugin_bazel.
Precompiled protoc_plugin:protoc_plugin.
Installed executable protoc-gen-dart.
Activated protoc_plugin 0.7.11.
```

**Comment by sigurdm** [comment]
Are you using a mirror?
What is your 'PUB_HOSTED_URI' environment variable set to?

**Comment by skyzh** [comment]
Hi! @hjlp20150803 just submitted an issue at our mirror site. 
https://github.com/sjtug/mirror-requests/issues/70

I'm not sure if this issue is related to the mirror site, as we just act as a reverse proxy to https://pub.dev .  https://dart-pub.mirrors.sjtug.sjtu.edu.cn/packages/protoc_plugin

**Comment by hjlp20150803** [comment]
> Are you using a mirror?
> What is your 'PUB_HOSTED_URI' environment variable set to?

It just can't work, upgrading failed again and again, I can't remember how many times I tried weather with 'PUB_HOSTED_URI' set or not, even I removed all the dart and reinstalled,looks like below:
================================
$ pub global activate protoc_plugin
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies... (7.1s)^C
longxhb:~ longxhb$ pub global activate protoc_plugin 19.0.1
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies... (5:37.8s)
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.

**Comment by hjlp20150803** [comment]
> Are you using a mirror?
> What is your 'PUB_HOSTED_URI' environment variable set to?

It just can't work, upgrading failed again and again, I can't remember how many times I tried weather with 'PUB_HOSTED_URI' set or not, even I removed all the dart and reinstalled,looks like below:
```
$ pub global activate protoc_plugin
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies... (7.1s)^C
longxhb:~ longxhb$ pub global activate protoc_plugin 19.0.1
Package protoc_plugin is currently active at version 0.7.11.
Resolving dependencies... (5:37.8s)
It looks like pub.dartlang.org is having some trouble.
Pub will wait for a while before trying to connect again.
```

**Comment by sigurdm** [comment]
I think this is due to https://github.com/dart-lang/pub/issues/2477

**Comment by hjlp20150803** [comment]
> I think this is due to [dart-lang/pub#2477](https://github.com/dart-lang/pub/issues/2477)

I have upgraded the protoc_plugin to 19.0.1,but when I "$ protoc  ./test.proto --dart_out=grpc:./dart",I got "--dart_out: protoc-gen-dart: Plugin output is unparseable".

Could you please help me to take a look?


```
$ pub global activate protoc_plugin 19.0.1
Package protoc_plugin is currently active at version 19.0.1.
Resolving dependencies... (2.6s)^C
$ dart --version
Dart VM version: 2.9.0-11.0.dev.flutter-6489a0c68d (be) (Wed May 27 05:50:13 2020 +0000) on "macos_x64"
$ pub --version
Pub 2.8.3


test.proto:
syntax = "proto3";

// option java_multiple_files = true;
// option java_package = "io.grpc.examples.helloworld";
// option java_outer_classname = "HelloWorldProto";

//package agent;
package bridge;

message LoadKeysRequest {
	string Addr = 1; 
	string RPass = 2; 
	string IPass = 3; 
	string N = 4;
	string U = 5;
}
message LoadKeysFromRequest {
	string Pass=1; 
	//BasicDataLocation byte
	string FileName=2; 
}

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```
$ protoc  ./test.proto --dart_out=grpc:./dart

[pluginoutput.txt](https://github.com/dart-lang/protobuf/files/4718083/pluginoutput.txt)

**Comment by osa1** [comment]
Latest version of protoc_plugin generates these methods, please update protoc_plugin.
