### ISSUE TITLE
but code generator protoc-gen-dart hasn't been updated to support optional fields in proto3.

### ISSUE THREAD

**Issue by girirajthara** [google/protobuf.dart#396]
when using optional in proto3 file we generated python code but not dart

**Comment by mraleph** [comment]
@iinozemtsev @sigurdm I see that internal fork supports optional. Any plans to bring repos in sync?

**Comment by iinozemtsev** [comment]
Yes, I slowly work on syncing these repos, once I finish with null safety, I'll bring proto3 optional support

**Comment by enyo** [comment]
@iinozemtsev how do I proceed at the moment if I want to build an API with optional values? I have an `UpdateRequest` message, and I want most values to be optional so the client can decide which values to update. What is the way to go here?

I've seen that some recommend `oneof` but that's more of a hack than anything else, and it also doesn't work with repeated values.
