### ISSUE TITLE
pub install fails for protoc_plugin

### ISSUE THREAD

**Issue by jeremyherbert** [google/protobuf.dart#410]
I have dart installed on Ubuntu 18.04 and I'm trying to get the protobuf generator working. When I run `pub install`, I get the following error:

```
$ pub install
Resolving dependencies... (1.2s)
Because protoc_plugin depends on protobuf ^1.1.0 which doesn't match any versions, version solving failed.
```

**Comment by jeremyherbert** [comment]
FWIW, this is clearly because 1.1.0 doesn't exist in: https://pub.dev/packages/protobuf/changelog

**Comment by osa1** [comment]
Closing as the error message is saying there isn't a version matching `^1.1.0` and we currently have multiple versions matching that.
