### ISSUE TITLE
Number fields from Firestore DocumentSnapshot data map can't be read properly with _mergeFromProto3Json?

### ISSUE THREAD

**Issue by waj334** [google/protobuf.dart#411]
I'm writing my protobuf messages directly to Firestore documents and I'm having a issue with converting those documents back into protobuf objects. The issue is "number" fields from a Firestore document seem to always be returned as a double and any case where an int is expected fails. Can double/int permissiveness be optional for this function?

**Comment by osa1** [comment]
> Can double/int permissiveness be optional for this function?

I'm not sure what this means. Could you give a concrete example of what do you want to be different in this library?
