### ISSUE TITLE
Support for NNBD

### ISSUE THREAD

**Issue by kekland** [google/protobuf.dart#415]
Hello!

I just switched the codebase in my app to use Dart's new NNBD feature (Dart version v2.10.0), but I can't migrate to NNBD fully because the `protoc`'s generated `.dart` files don't support NNBD. Is there something that I'm missing (maybe a compiler option), or if not, is the support for it planned?

**Comment by iinozemtsev** [comment]
Hi, could you try https://pub.dev/packages/protobuf/versions/2.0.0-nullsafety.0?

**Comment by kekland** [comment]
Hi! NNBD is not the priority at the moment but will check it out later. Thanks for the update!
