### ISSUE TITLE
big message considered corrupt

### ISSUE THREAD

**Issue by ekasetiawans** [google/protobuf.dart#449]
tried to send a message over 20 MB in size but failed and was considered corrupt.
grpc 2.8.0

the current solution is to change the **DEFAULT_SIZE_LIMIT** in the protobuf repository in `protobuf/lib/src/protobuf/coded_buffer_reader.dart` to 200MB.

**Comment by ekasetiawans** [comment]
related to grpc/grpc-dart#411

**Comment by sigurdm** [comment]
Hmm when you are sending the message it should not have to go through coded_buffer_reader...

Is this when you are receiving a message?

It would be nice if we had a way to configure this limit when setting up a grpc-server.

**Comment by ekasetiawans** [comment]
@sigurdm I have set the max message size in grpc server (using go language). it works perfectly if I use grpc client for C#.
all bytes have been received, but an error appears when parsing bytes

**Comment by sigurdm** [comment]
Sorry - I'm not sure I follow your setup exactly.

Are you receiving or sending from dart?

If you are sending from dart you should never get to parse the bytes.

**Comment by ekasetiawans** [comment]
@sigurdm receiving

**Comment by sigurdm** [comment]
Ah - ok. So the feature request really is for the dart grpc server...

**Comment by ekasetiawans** [comment]
@sigurdm I'm building an application using grpc, for the backend I use golang, and the frontend uses flutter / dart for mobile and also c # for the desktop. However, this problem occurs when I receive data from the server to the mobile. The same message I can receive fine on the desktop using c #.

as additional information, the data that I send is in the form of an array.

**Comment by osa1** [comment]
[`CodedBufferReader` constructor][1] takes an optional `sizeLimit` argument. Does it not solve this problem? Are you using `CodedBufferReader` indirectly? If you're using `CodedBufferReader` indirectly via another library perhaps this is a feature request for that library to add a `sizeLimit` argument to the library method(s) that calls `CodedBufferReader`.

[1]: https://pub.dev/documentation/protobuf/latest/protobuf/CodedBufferReader/CodedBufferReader.html

**Comment by osa1** [comment]
Related to the message size limit: #386.
