### ISSUE TITLE
Integrate grpc gateway for nakama flutter 

### ISSUE THREAD

**Issue by Allan-Nava** [google/protobuf.dart#505]
I'm trying to create a plugin for [nakama](https://github.com/heroiclabs/nakama), but I have problem to integrate grpc gateway.
<img width="1438" alt="Screenshot 2021-04-22 at 22 07 34" src="https://user-images.githubusercontent.com/22498435/115778695-5aa46d00-a3b7-11eb-9084-a19ac70583eb.png">

This is the repository:  https://github.com/Allan-Nava/nakama-flutter

**Comment by srikrsna** [comment]
[gRPC gateway](https://github.com/grpc-ecosystem/grpc-gateway) is a way to transcode HTTP1.1/JSON call to gRPC. This is not related to this plugin.

To use this plugin you will need a gRPC server not the gRPC Gateway. If you only have the gateway then a better way would be to generate a HTTP/JSON client from the Open API spec generated by gRPC Gateway

**Comment by osa1** [comment]
This doesn't seem to be related with this library. Please feel free to reopen if you disagree.
