### ISSUE TITLE
Protobuf generated code needs to ignore prefer_constructors_over_static_methods, constant_identifier_names, directives_ordering, 

### ISSUE THREAD

**Issue by jonahwilliams** [google/protobuf.dart#506]
On an attempted update of the flutter_reactive_ble package, all of these diagnostics were surfaced (unsure why they're not running now, possibly a pedantic update?) If these rules have changed then the protobuf generated code should either be updated or ignore them

See https://github.com/PhilipsHue/flutter_reactive_ble/pull/271

**Comment by osa1** [comment]
`directives_ordering` and `constant_identifier_names` are ignored in master branch (possibly not in the latest release): https://github.com/google/protobuf.dart/blob/5e1a422e39476884861a2137b0d7241315889299/protoc_plugin/lib/src/file_generator.dart#L634-L648

Do we still need to ignore `prefer_constructors_over_static_methods`?

**Comment by osa1** [comment]
Latest release of protoc_plugin generates code that passes lints-1.0 lints, and the next version will generate code that passes lints-2.0 lints. Closing as fixed.
