### ISSUE TITLE
Consider sorting directives in generated code (to agree w/ `directives_ordering`)

### ISSUE THREAD

**Issue by pq** [google/protobuf.dart#511]
It would be great if generated code had sorted imports that agree with Dart sorting conventions.  In practice, folks use the [`directives_ordering`](https://dart-lang.github.io/linter/lints/directives_ordering.html) lint from the [Dart Linter](https://github.com/dart-lang/linter) to enforce this.

See https://github.com/grpc/grpc-dart/pull/479#discussion_r642367280 for an example of where this is tripping people up in the wild.

/fyi @mraleph

**Comment by osa1** [comment]
Closing as duplicate of #506.
