### ISSUE TITLE
Should mention `grpc` option and give an example

### ISSUE THREAD

**Issue by gmpassos** [google/protobuf.dart#516]
If you want to use the package `grpc` (https://pub.dev/packages/grpc), the actual way to use protobuf in Dart, you need the generated client classes

If the option `grpc` is not passed while generating the Dart code, the API/Service Clients won't be generated (*.pbgrpc.dart).

An example showing the need of this option is very important:

`protoc --dart_out=grpc:./dart-gen-dir -Iproto proto/foo/foo_service.proto`

**Comment by osa1** [comment]
Done in #514 (merged as c26ac34ff460ca697f440d0be507b0e6b707e73c).
