### ISSUE TITLE
API for creating read-only protobufs

### ISSUE THREAD

**Issue by skybrian** [google/protobuf.dart#53]
We would like a way to create read-only GeneratedMessages, using some kind build or freeze API.

An important use case is to storing read-only data in a cache and passing out references to it without corrupting the cache.

Some issues to consider:
- Is it recursive?
- Do we need to freeze in place or is creating a read-only clone acceptable?
- Do we need to unfreeze it?
- Do we want read-only types? That is, for message Foo, should we also have ReadonlyFoo?

**Comment by skybrian** [comment]
@DavidSouther created a pull request: https://github.com/dart-lang/dart-protobuf/pull/51

**Comment by skybrian** [comment]
A fairly clean API might be to add cloneReadonly() which recursively creates an immutable clone. This would allow people to build a tree of messages using the regular API and then freeze it, recursively, without affecting the original. A downside would be the performance hit from doing the clone operation.

Calling clone() would get you a mutable copy again.

readonlyClone() could also return a different type which might be useful sometimes, but that would require modifying the protoc plugin to generate ReadonlyFoo for each message Foo. It's more work, and would force people decide whether to accept a Foo or ReadonlyFoo in their API's.

**Comment by zoechi** [comment]
I guess an immutable `Foo` and an `MutableFoo extends/implements Foo` would be better than `ReadonlyFoo`. This way accepting `Foo` would allow both and a `MutableFoo` would needed to be requested explicitly instead of the other way around.

**Comment by skybrian** [comment]
If we end up generating a mutable and immutable type per message, logically neither one should a subtype of the other because neither one can substitute for the other. (Just like String and StringBuffer are separate types and you wouldn't want one to substitute one for the other.) We could also have a common superclass but that would mean generating three classes per message.

Also, it would be a painful migration to change all existing code to use a different type and much easier for the read-only variant to get the new name. This is why I suggest having Foo and ReadonlyFoo if we do it at all.

Having multiple types to choose from per message seems cleaner conceptually, but it does add complexity. We have to decide whether the extra compile-time checks are worth it, or whether it's okay in this case to throw runtime exceptions.

**Comment by DavidSouther** [comment]
I opened #51 because my team needs some guarantee of immutability ASAP. The most direct approach is to add some method that sets the _isReadOnly flag on GeneratedMessage (which as of today is a constant false), and clean up `_isReadOnly` usage in `SetField` and elsewhere. Cleaning up `SetField` seems like it would be a good code health task anyway.

For the method name, `freeze` is too generic, and is used elsewhere in Github and internal Google products. `freezeMessage` [is available](https://www.google.com/search#as_qdr=all&q=%22freezeMessage%22+site:github.com+inurl:.dart). I am highly suspicious of this being recursive - it'd be very easy to pass a reference to a contained message, in which case recursively freezing is going to give someone else a very bad time. I'd rather see a second method, `freezeClone` ([available](https://www.google.com/search?q=%22freezeClone%22+site:github.com+inurl:.dart)), that does a recursive clone & freeze.

I think these two additions would be useful, and a minimal amount of effort.

Having a dedicated Builder UI for messages generated by `dart-protoc-plugin` would be nice, but would be more work than I have time to commit.

**Comment by skybrian** [comment]
I'm okay with implementing freezeClone() and thinking about new types later.

By allowing frozen messages at all, we risk runtime errors when they are passed to API's that expect a mutable message, and type-checking won't help us. But this is detecting a probable bug. Detecting it at runtime seems better than not detecting it at all.

Currently we use _isReadOnly to implement read-only default values for messages. (It is overridden in ReadonlyMessageMixin.) This is why it isn't fully implemented for repeated fields - in the case of a default value, all repeated fields are empty. You can look at ReadonlyMessageMixin to see the other things that have to change.

**Comment by DavidSouther** [comment]
Would you be okay with `freezeMessage()` first, then implementing `freezeClone()` on top of that, or would you rather it be `_freezeMesage()` to start with?

**Comment by skybrian** [comment]
Let's keep it private for now.

I'm wary of letting people freeze arbitrary messages, but _freezeMessage() seems like a good primitive for implementing public API's such as freezeClone(), or perhaps new constructors such as GeneratedMessage.fromJsonFrozen().

Naming: since it's private, _freezeMessage() could just be _freeze().
Perhaps rename freezeClone() -> cloneFrozen()?

**Comment by skybrian** [comment]
So, about recursion: I'm wary of getting into a situation where frozen messages can have non-frozen children. Seems like once we allow that we'll end up supporting it forever. For people who want an immutable message, it seems like you probably want it to be immutable all the way down?

So I think maybe can start with cloneFrozen() and see if we can live with it? For trees that are mostly frozen, there's not going to be much work to clone them.

The reverse case (mutable parents with frozen children) is going to happen automatically unless we put in runtime checks preventing it. I'm inclined to allow it, and maybe add a mutableFoo() method next to each message field setter that makes the child mutable if it's not already.

**Comment by skybrian** [comment]
The rebuild() method that @davidmorgan mentioned seems interesting. Perhaps we can generate the following on subclasses of GeneratedMessage:

typedef void FooMutator(Foo f);

Foo cloneFrozen([FooMutator mutator]);

The idea would be that if Foo is frozen and a mutator is supplied, we clone the top-level message and any mutable child messages,  and call the mutator. It makes whatever changes needed (possibly thawing child messages with mutableBar() methods). When it returns, we freeze (in place) whatever is still mutable in the tree.

This would give us the ability to do arbitrary mutations of a tree while making only one copy of each node that actually changed in the tree.

**Comment by skybrian** [comment]
We met in person yesterday to talk about the API. I'll summarize here.

Here's the use case they're interested in: The application code sends protobuf requests to an RPC system and gets back responses. When sending a request, they want to use the request (or part of it) as a map key in a cache. For safety this requires either copying the key or freezing it.

To avoid a copy, the idea is that when you send a request, it *transfers ownership* to the RPC system. Once ownership is transferred, it's an error for the caller to modify the request. So, freezing the protobuf in place is exactly what they want to do.

Ownership transfer can't be represented in Dart's type system (it would require something like Rust). The best way we can handle this is to throw a runtime error.

When we think about it in these terms, I don't see any particularly strong objection to making the freeze method public. It can be used incorrectly in cases when the protobuf's owner is unclear. But sharing mutable objects with unclear ownership is kind of dicey anyway.

We decided that unfreeze() is not necessary. I think we decided to freeze the protobuf recursively (mixtures of frozen and mutable objects don't seem useful) but I'm a bit hazy on that.

**Comment by davidmorgan** [comment]
Sounds good.

I think it's worth mentioning for the record that if you don't specifically need protos, https://github.com/google/built_json.dart is another serialization mechanism for Dart that is built around immutable types. It's not yet 100% ready but it's not far off either. For those who happen to work at Google we have an internal-only version that's production ready and in use.

**Comment by osa1** [comment]
The `freeze` API discussed here (along with `rebuild`) was already implemented a while ago. Closing.
