### ISSUE TITLE
github.com/google/protobuf moved to github.com/protocolbuffers/protobuf?

### ISSUE THREAD

**Issue by awly** [google/protobuf.dart#532]
Up until recently, github.com/google/protobuf hosted the main protobuf compiler (or at least the releases for it).
Some doc references still point to it, like https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os and https://developers.google.com/protocol-buffers/docs/downloads (the Old Versions link).

Now, github.com/google/protobuf redirects to github.com/google/protobuf.dart.
https://github.com/protocolbuffers/protobuf appears to be the new home of the compiler.

Were the repos moved recently? Some of [our build automation](https://github.com/gravitational/teleport/blob/bad6702adb9d74c84a8a250cf307c3f2ebcd5327/build.assets/Dockerfile#L113) is now failing to download a tagged release from this github repo. Seems like this would break a lot of other users too.

**Comment by wasauce** [comment]
Our build is also breaking because of this change. Did it just happen?

**Comment by kent-id** [comment]
I can confirm the same, looks like it just started happening. My build fails with 404 error when downloading https://github.com/google/protobuf/releases/download/v3.9.0/protoc-3.9.0-linux-x86_64.zip

**Comment by thejohnfreeman** [comment]
It seems they've fixed the problem now by fixing the redirect. https://github.com/google/protobuf now redirects to https://github.com/protocolbuffers/protobuf

**Comment by awly** [comment]
Great, the redirect is fixed.
I'm updating our references of `github.com/google/protobuf` to `github.com/protocolbuffers/protobuf`, and suggest others do the same.
