### ISSUE TITLE
json_serializable incompatible

### ISSUE THREAD

**Issue by QonvexTech** [google/protobuf.dart#537]
I am currently working with a package that uses json_serializable 4.1.4 and it requires dart_style ^2.0.0 currently protoc_plugin is on dart_style ^1.0.6

**Comment by JishnuM** [comment]
Using a dependency override worked for me in a similar scenario.

But +1 that the `dart_style` dependency is rather out of date, please consider a release now that it is updated on `master`.

**Comment by osa1** [comment]
Closing as this is fixed in master branch.
