### ISSUE TITLE
[ask ]Two Different package names but they are   same content, Is the two proto file  Encode is  same?

### ISSUE THREAD

**Issue by seifeHu** [google/protobuf.dart#545]
Two Different package names but they are   same content, Is the two proto file  Encode is  same?

**Comment by osa1** [comment]
Could you elaborate please? What do you mean by "different name but same content"?

Protobuf binary encoding does not care about field or message names, so names do not matter. If your messages are structurally the same then they're encoded the same way.

JSON encoding however uses names (which IMO is a misfeature), so names matter if you're using proto3 JSON encoding.

Please feel free to reopen if this doesn't answer your question.
