### ISSUE TITLE
Utilize nanopb protofile

### ISSUE THREAD

**Issue by lalarsson** [google/protobuf.dart#558]
Hi!

I've got a protofile with an `nanopb.proto` import statement that I'd like to utilize for my dart project but I can't seem to get the import statement to work.
How can I get plugins like `nanopb` to compile to dart?

Thanks in advance for any help!

**Comment by osa1** [comment]
When using imports make sure you pass the right `-I` flags to `protoc`. See https://developers.google.com/protocol-buffers/docs/proto3#importing_definitions for details (last paragraph).

By "nanopb" if you mean https://jpa.kapsi.fi/nanopb/, that seems to be a protobuf implementation for C, not Dart.

I don't think this is a bug in this library. Please feel free to re-open if you disagree. For user questions please use the "Discuss" tab.
