### ISSUE TITLE
Code generator import redundant

### ISSUE THREAD

**Issue by ZanderZhan** [google/protobuf.dart#569]
After update flutter to 2.8.1, dart analysis produce a lot import issue, such as 

```
info: The import of '***.pbenum.dart' is unnecessary because all of the used elements are also provided by the import of '../core/****.pb.dart'. (unnecessary_import at ....)
```

**Comment by osa1** [comment]
This is working as intended. You don't need to import the enum file if you're already importing the file for your proto definition. Remove the `pbenum.dart` import.
