### ISSUE TITLE
 A library can't opt out of null safety by default, when using sound null safety.

### ISSUE THREAD

**Issue by LiJinJinJIn** [google/protobuf.dart#571]
![image](https://user-images.githubusercontent.com/77655423/148903158-d78fff27-3983-4eda-a661-4beb5dea1cb0.png)

**Comment by osa1** [comment]
This question was also asked in [grpc-dart](https://github.com/grpc/grpc-dart/issues/537). Copying the answer here in case someone comes across this issue:

> Regenerate your proto files using a newer version of the protoc plugin which produces NNBD compatible code.

I think NNBD means "non-nullable by default".
