### ISSUE TITLE
Performance cliff when running apps with many protobuf classes

### ISSUE THREAD

**Issue by mkustermann** [google/protobuf.dart#573]
When running apps with many proto classes one can run into a performance cliff due to doing runtime function type checks in the Dart VM (which are currently implemented via a cache that has maximum size).

The "offending" code in the protobuf library is in [generated_message](https://github.com/google/protobuf.dart/blob/a7e75cb9b2efe9fb8f10212/protobuf/lib/src/protobuf/generated_message.dart#L514):
```dart
  static final Map<Function?, Function> _defaultMakers = {};

  static T Function() _defaultMakerFor<T extends GeneratedMessage>(
      T Function()? createFn) {
    return (_defaultMakers[createFn] ??= _createDefaultMakerFor<T>(createFn!))
        as T Function();
  }
```

When inserting `createFn` into the `Map<Function?, Function>` we loose track of its function type `T Function()?`. That means when getting it out of the map we have to do a runtime function type check which is very expensive.

**Comment by mkustermann** [comment]
We could land a change that replaces this runtime function type test with a simpler runtime interface type check that is more efficiently implemented in the Dart VM.

See PR https://github.com/google/protobuf.dart/pull/574

/cc @sstrickl

**Comment by mraleph** [comment]
@mkustermann I presume this is fixed by your PR?

**Comment by mkustermann** [comment]
Those particular function type checks are gone now, yes.
