### ISSUE TITLE
protoc Plugin Build Instructions Clarification

### ISSUE THREAD

**Issue by russoj88** [google/protobuf.dart#576]
Is the plugin actually standalone?  Not sure if I'm missing something or have a misunderstanding.

This is from [Wikipedia](https://en.wikipedia.org/wiki/Standalone_program):
> A stand-alone program, also known as a freestanding program, is a computer program that does not load any external module, library function or program and that is designed to boot with the bootstrap procedure of the target processor – it runs on bare metal.

After [building the plugin](https://github.com/google/protobuf.dart/tree/master/protoc_plugin#how-to-build-and-use), the executable is a script that calls dart, so this is not standalone.

If I am correct so far, is there a way to build a standalone binary (no dependencies)?

**Comment by russoj88** [comment]
I ended up using `dart compile` to create a binary.  Not sure if this should go in the README or not.

**Comment by russoj88** [comment]
@osa1 thanks for following up.

1. The dependencies that are shared objects were not a problem for my use. The main issue was the dependency on dart itself. I'm compiling protobufs on a different machine than my dart development.
That being said, static would be appreciated.
2. The following is output from `protoc --help`:
```shell
--plugin=EXECUTABLE         Specifies a plugin executable to use.
                              Normally, protoc searches the PATH for
                              plugins, but you may specify additional
                              executables not in the path using this flag.
                              Additionally, EXECUTABLE may be of the form
                              NAME=PATH, in which case the given plugin name
                              is mapped to the given executable even if
                              the executable's own name differs.
```
I don't think the plugin has to have a specific name.

**Comment by osa1** [comment]
@russoj88 I tried to address this in #610. Any feedback would be appreciated.

**Comment by russoj88** [comment]
> @russoj88 I tried to address this in #610. Any feedback would be appreciated.

That would have saved me quite a bit of time when I was trying to build before :) Thanks.
