### ISSUE TITLE
Feature request: Wrap protoc with Dart Build system 

### ISSUE THREAD

**Issue by mhoad** [google/protobuf.dart#650]
My experience so far in using prtotobufs in Dart has for the most part been OK but I’ve noticed a decent amount of time seems to get spent each project on doing things like writing Makefiles to do things like download the latest protoc compiler, run it against all the proto files in a project, run dart format over the resulting output etc.

Given that dart already has a really nice hermetic build system I wanted to submit a feature request that we take use of it to deliver a really smooth / integrated experience to reduce the friction of using protobufs / gRPC in a project.

**Comment by osa1** [comment]
Thanks for reporting. We are aware of this issue and we have two issues to track this: #158, #382. Closing as duplicate.
