### ISSUE TITLE
[proposal] exclude generated files from code coverage

### ISSUE THREAD

**Issue by iapicca** [google/protobuf.dart#768]
### Use case

currently generated files negatively affect code coverage

### Proposal

add the comment `// coverage:ignore-file`, 
made available by [dart tools coverage](https://pub.dev/packages/coverage) (see https://github.com/dart-lang/coverage/pull/302),
to the generate files to exclude these from coverage

cc @osa1

**Comment by osa1** [comment]
Thanks for the ping. Could you give us some context please? What is coverage? How do you run it? What's the problem not having `// converage:...` causes?

**Comment by osa1** [comment]
Hi @iapicca. We discussed this briefly and coverage devs opened an issue for adding a command line flag to coverage to ignore files: https://github.com/dart-lang/coverage/issues/427. This coverage feature is much more general, you can ignore files generated by other code generators as well, and with that feature we don't need to change anything in this library.

**Comment by iapicca** [comment]
Fair enough, thanks for checking this out @osa1 

For anyone that is reading this issue and uses [codecov](https://about.codecov.io/)
you may also add to your `codecov.yml`
```yaml
ignore:
  - '**/*.pb.dart'
```
