### ISSUE TITLE
improve the readability of the generated code

### ISSUE THREAD

**Issue by devoncarew** [google/protobuf.dart#771]
Hi; I have some ideas for changes that could improve the readability of the generated code. These would all be non-functional changes; they wouldn't effect the compiled size of the code or the runtime performance.

The readability of the generated code probably isn't a critical consideration here, so I thought I'd open an issue to discuss before sending PRs. Some potential changes:

- move the `n` copies of `const $core.bool.fromEnvironment('protobuf.omit_field_names')` in the generated files into a single `_omitFieldNames` const in each file
- address a few of the ~12 lints we ignore in the generated code

cc @osa1

**Comment by osa1** [comment]
@devoncarew we merged a few PRs about this, can this be closed as complete or do you have more changes planned?

**Comment by devoncarew** [comment]
I think we're good to close this - any other things we notice wrt readability can just be tackled at the time / filed as separate issues.
