### ISSUE TITLE
The named parameter 'valueDefaultOrMaker' isn't defined. 

### ISSUE THREAD

**Issue by lucagonzalez** [google/protobuf.dart#786]
After updating to the latest version `protobuf-2.0.1, protoc_plugin-20.0.1 ` my generated code came with an error when generating code.

When executing this line:

`protoc assessments.proto --dart_out=../../../../core/lib/generated/`

My file "assessments.pb.dart" comes with the following error:

![image](https://user-images.githubusercontent.com/34002560/209941910-e366a8e7-4e5a-497f-9feb-ee2c2d442674.png)

This started to happen after I updated to the latest version of the package.

**Comment by lucagonzalez** [comment]
I am also having this issue, I don't know if they are related:

https://github.com/google/protobuf.dart/issues/785

**Comment by osa1** [comment]
Could you share your proto file? Am I right that in the screenshot the `valueDefaultOrMaker` is passed to a `pc` method?

I think I probably found the bug, it would be easier for me to validate my fix if I had the proto definitions that cause this issue.

**Comment by lucagonzalez** [comment]
Thanks for answering!

Here's the proto file from that print:

```syntax = "proto3";
package classroom;

import "timestamp.proto";


message AssessmentsFile {
  repeated AssessmentDefinition assessments = 1;
}

message AssessmentDefinition {
  string name = 1;
  string id = 2;
  string shortDescription = 3;
  string longDescription = 4;
  repeated AssessmentSectionDefinition sections = 5;
}

message AssessmentSectionDefinition {
  string id = 1;
  string name = 2;
  repeated AssessmentQuestion questions = 4;
}

message AssessmentQuestion {
  string text = 2;
  bool isInventedWord = 3;
  string guidance = 4;
}

message PupilAssessment {
  string id = 1;
  string definitionId = 2;
  string pupilName = 3;
  Timestamp startTimestamp = 4;
  map<string, AssessmentAnswerSection> answerSections = 5;
}

message AssessmentAnswerSection {
  string sectionId = 2;
  map<string, AssessmentAnswer> answers = 3;
}

message AssessmentAnswer {
  string questionText = 2;
  PupilResponse response = 3;
  double durationInSeconds = 4;
  Timestamp changedTimestamp = 5;
}

enum PupilResponse {
  CORRECT = 0;
  INCORRECT = 1;
  NO_RESPONSE = 2;
}
```

This one has only messages defined. On #785 the problem appears when defining services

**Comment by osa1** [comment]
You seem to be using a more recent version of protoc_plugin than the latest released version. I just tried your example, if you use the latest releases (from pub.dev) of protobuf library and protoc_plugin it should work.

The change that causes the compile error you show was done in #745 which is not released yet. Last release was done with 53f756a0eebe5377e76ac5b483e2007e22467f8d (Jun 15, 2022), #745 was merged as bdd90b2b6d2ffe431aceaa3145ed40393d4acb0c (Sep 1, 2022).

**Comment by osa1** [comment]
I think we should probably mention protoc_plugin version number in the comment lines we generate at the beginning of files, e.g. `// Generated by protoc_plugin-x.y.z` instead of just `// Generated code. Do not modify.`. Would be helpful when debugging.

**Comment by lucagonzalez** [comment]
Thank you for explaining. 
You are right. Adding the protoc_plugin version number would be good when adding a bug request. I bet that I didn't upgrade the version correctly. Now I've built the standalone executable, and it worked. This is way better too for the team as we don't need to individually maintain the same version on each machine.

Thanks for your time!
