### ISSUE TITLE
Dart 3 incompatibility: ProtobufEnum instances can't be used in const maps

### ISSUE THREAD

**Issue by oprypin** [google/protobuf.dart#821]
If someone makes a `const` `Map` of proto enum members, as follows:

```dart
const items = {
  SomeProtoEnum.FOO: 'fooo',
  SomeProtoEnum.BAR: 'baar',
};
```

<details><summary>This happens with any enum, even the simplest one:</summary>

```protobuf
enum SomeProtoEnum {
  FOO = 0;
  BAR = 1;
}
```
```dart
class SomeProtoEnum extends $pb.ProtobufEnum {
  static const SomeProtoEnum FOO = SomeProtoEnum._(0, const $core.bool.fromEnvironment('protobuf.omit_enum_names') ? '' : 'FOO');
  static const SomeProtoEnum BAR = SomeProtoEnum._(1, const $core.bool.fromEnvironment('protobuf.omit_enum_names') ? '' : 'BAR');
[...]
```

</details>

---

In Dart 2.19 that works fine.

But in Dart 3.0 it shows this error:

```
CONST_MAP_KEY_NOT_PRIMITIVE_EQUALITY
The type of a key in a constant map can't override the '==' operator, or 'hashCode', but the class 'SomeProtoEnum' does.
```

---

Indeed, the base `class ProtobufEnum` has these definitions that clearly cause this:

https://github.com/google/protobuf.dart/blob/b90a4c44d56075eb23ee38ae56ce0febfd7f280f/protobuf/lib/src/protobuf/protobuf_enum.dart#L53-L57

They seem to serve no purpose though, as far as I can tell. Maybe they can just be deleted and then compatibility with all versions of Dart will be preserved?

**Comment by sigurdm** [comment]
Yeah the instance-based hash-code would probably work fine.

**Comment by oprypin** [comment]
This breakage will affect any file that is at Dart language version 3.0, whether or not the protobuf library or its generated proto definitions switch to language version 3.0.

@kevmoo @devoncarew @scheglov What do you think? Would you agree to delete these definitions soon (and make a release)? It seems totally safe to do and doesn't require waiting. Otherwise real users will start running into this issue soon.

**Comment by kevmoo** [comment]
@oprypin – don't have a lot of context, but deleting seems like the right idea.

Although we need to be careful about NON-const hashCode, right?

**Comment by scheglov** [comment]
Theoretically, if these are enum constants, we don't are not supposed more than one instance of them, and so the default `hashCode` from `Object` will be enough.

But I don't know for sure how protobuf is supposed to work.
IIRC I have never worked on it.

**Comment by oprypin** [comment]
> so the default hashCode from Object will be enough.

The thing is, I don't think there's ever a re-definition of hashCode, this empty override declaration seems to be all there is. And when I say remove, I remove just the empty declaration (nothing else to be removed) and everything keeps working.

**Comment by oprypin** [comment]
Ah sorry, never mind, it *does* say `hashCode => value`, so of course it's not empty
