### ISSUE TITLE
Any plans to support dart3

### ISSUE THREAD

**Issue by mfridman** [google/protobuf.dart#829]
I was browsing https://dart.dev/resources/dart-3-migration and then wondered if there are any plans to update the build to use dart 3?

Also, are there plans to publish a new version? https://pub.dev/packages/protoc_plugin/versions

**Comment by peterweb2005** [comment]
yes, seems related to the error, when trying runing protoc:

can't load kernel binary: invalid kernel binary format version

**Comment by Pacane** [comment]
@kevmoo do you know what's blocking this? This might be blocking our adoption of latest flutter web / dart 3 right now.

**Comment by kevmoo** [comment]
@mraleph ?

**Comment by sigurdm** [comment]
@peterweb2005 and @ashishdock you might have been hit by https://github.com/dart-lang/sdk/issues/52386.

If that is the case you should delete the cache at C:\Users\<user>\AppData\Roaming\Pub\Cache\bin and point your PATH variable to C:\Users\<user>\AppData\Local\Pub\Cache\bin and things should work again.

**Comment by peterweb2005** [comment]
thanks, 
prompt error disappeared

**Comment by osa1** [comment]
We just published protobuf-3.0.0 and protoc_plugin-21.0.0.
