### ISSUE TITLE
Publish version 3.0.0

### ISSUE THREAD

**Issue by derekxu16** [google/protobuf.dart#837]
The Dart SDK has a check that ensures that dependency constraints in our packages are compatible with the versions of packages pulled in by the `DEPS` file. The version of `package:protobuf` in `DEPS` is `3.0.0-dev`, but there is no published version of `package:protobuf 3.0.0`. This means that the check is currently stopping us from using both `package:protobuf: ^2.0.0` and `package:protobuf: ^3.0.0` as constraints in our packages. Publishing `package:protobuf 3.0.0` would fix this.

See https://dart-review.googlesource.com/c/sdk/+/303022/comment/d77751a4_f9e8fea8/ for more details.

**Comment by a-siva** [comment]
//cc @osa1

**Comment by sigurdm** [comment]
You can use `protobuf: ^3.0.0-dev` as a constraint. Or, if you are not affected by breaking changes between 2 and 3 `protobuf: >=2.0.0 <4.0.0`.

**Comment by osa1** [comment]
We just released protobuf-3.0.0 and protoc_plugin-21.0.0.
