### ISSUE TITLE
How do you generate via buf?

### ISSUE THREAD

**Issue by Galaf** [google/protobuf.dart#865]
Hello!

I tried generating the base files and it is perfectly OK but I can't generate the gRPC files.
Trying to use something like:

```yaml
  - plugin: buf.build/protocolbuffers/dart:v21.0.2
    out: "grpc:proto/dart"
```

will fail with the following error message:

```
The filename, directory name, or volume label syntax is incorrect.
```

I tried several variations such as 
1) same `out` but with a comma to separate the options.
2) separate plugin entry with a `grpc:` prefix.

But it doesn't seem to work anyway.

Thank you in advance for your help.

**Comment by utamori** [comment]
```dart
version: v1
plugins:
  - plugin: buf.build/protocolbuffers/dart:v20.0.1
    out: lib
    opt:
      - grpc
```

**Comment by Galaf** [comment]
Thank you, it worked!
