### ISSUE TITLE
Implement `package` specifier

### ISSUE THREAD

**Issue by RdeWilde** [google/protobuf.dart#90]
Any way to implement the package option?

https://developers.google.com/protocol-buffers/docs/proto3#packages

**Comment by osa1** [comment]
I think we could generate `library ...;` lines for `package` specifiers in proto files. Any thoughts on this @sigurdm?

**Comment by RdeWilde** [comment]
Too long ago for me, but dart_package sounds like the same thing yeah @sigurdm

**Comment by osa1** [comment]
OK, thanks for the update. Closing this one in favor of #295 as that one has more details.
