### ISSUE TITLE
Generated gRPC client method stubs get no comments or deprecation annotations

### ISSUE THREAD

**Issue by calmh** [google/protobuf.dart#900]
It would be nice if comments on rpc:s in the proto files were passed on as comments on generated method stubs. It would also be nice if `option deprecated = true` resulted in a `@Deprecated` annotation. Currently none of these things happen; for example,

```
// Deprecated: use GetLatestReportV2 (1.18.3)
rpc GetLatestReport(GetLatestReportRequest) returns (AerodromeReport) {
    option deprecated = true;
}
```

generates as

```
  $grpc.ResponseFuture<$8.AerodromeReport> getLatestReport($12.GetLatestReportRequest request, {$grpc.CallOptions? options}) {
    return $createUnaryCall(_$getLatestReport, request, options: options);
  }
```

which the client has no idea is deprecated, and gets no guidance from a comment.

**Comment by osa1** [comment]
#908 implements generating deprecated annotations, #909 implements generating comments.
