### ISSUE TITLE
Error: A value of type 'List<dynamic>' can't be returned from the function 'symbol' because it has a return type of 'PbList<ProtoOALightSymbol>'

### ISSUE THREAD

**Issue by JasperEssien2** [google/protobuf.dart#924]
It seems the mismatch is caused by protobuf generating a list with type `PbList<E>` while the `GeneratedMessage` abstract class and `FieldSet` class `_$getList<T>()` method signature returns a `List<T>` type.

Here's the `GeneratedMessage` class method declaration.
```dart
  List<T> $_getList<T>(int index) => _fieldSet._$getList<T>(index);
```

Meanwhile, the generated file
```dart
  @$pb.TagNumber(3)
  $pb.PbList<$1.ProtoOAAsset> get asset => $_getList(2);
```

**Comment by fawdlstty** [comment]
Hello, I have encountered the same problem. Can you tell me how you solved it?

**Comment by FR15** [comment]
I  changed the version of protoc_plugin to match the version of protobuf. It works now.
