### ISSUE TITLE
Add iOS privacy manifest

### ISSUE THREAD

**Issue by lauroboeni** [google/protobuf.dart#928]
This plugin is listed on https://developer.apple.com/support/third-party-SDK-requirements/ as requiring a privacy manifest. As far as I see, this declaration has not yet been made in this package. **The deadline is May 1, 2024**.

Please add a privacy manifest to your library.

**Comment by sebastianbuechler** [comment]
Here is an example of flutter_appauth with the required file: https://github.com/MaikuB/flutter_appauth/blob/master/flutter_appauth%2Fios%2FResources%2FPrivacyInfo.xcprivacy

This is important as all flutter developers won't be able to submit their apps to the App Store starting in a week!

**Comment by mraleph** [comment]
You are confusing Protobuf framework listed on that page with protobuf package, which is not listed there.

Protobuf package does not contain or use any native frameworks itself and as such does not need privacy manifest.
